input_data = open('input.txt', 'r') 
data = input_data.read()
data = data.split()
a = int(data[0])
output_data = open('output.txt','w')
output_data.write(str (2 ** a))
input_data.close()
output_data.close()